name: Run Tests on Push to session-1 and Pull Request to main

on:
  push:
    branches:
      - session-1
  pull_request:
    branches:
      - main
jobs:
  deploy:
      runs-on : ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java code
        uses: actions/setup-java@v4.3.0
        with:
            java-version: '21'
