name: Run Tests on Push to session-1 and Pull Request to main

on:
  push:
    branches:
      - session-1
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWOR}}
    - name: Build docker image
      run: docker build -t shastriswaroop/springboot-demo
    - name: Publish image to docker hub
      run: docker push shastriswaroop/springboot-demo:latest
